# Generated by Django 3.2.9 on 2021-12-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='booking_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='booking_start_date',
            field=models.DateField(null=True),
        ),
    ]
