# Generated by Django 3.2.9 on 2021-11-28 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_rating', models.IntegerField()),
                ('location', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.location')),
            ],
        ),
    ]
