# Generated by Django 3.2.9 on 2021-11-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_roombooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit.', max_length=500),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(default='hotel-1'),
            preserve_default=False,
        ),
    ]
