# Generated by Django 3.2.9 on 2021-11-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211128_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='slug',
            field=models.SlugField(default='blah'),
            preserve_default=False,
        ),
    ]
