# Generated by Django 3.2.9 on 2021-11-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_hotelroom_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='booking_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='booking_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
